### ISSUE TITLE
Cannot read property 'handler' of undefined on array.map item creation

### ISSUE THREAD

**Issue by SirSerje** [zkadish/nextiva-chess-game#1]
I've got error:
TypeError: Cannot read property 'handler' of undefined
on this code:
```
arr.map(function(name, index) {
  return <Field handler={this.handler} name={name} key={index} />;
}
```
Does anybody knows, how to solve this issue?

**Comment by SirSerje** [comment]
Sorry, forgot about looping in jsx.
This link completely solves my issue : [stackOverflow](https://stackoverflow.com/questions/22876978/loop-inside-react-jsx)

**Comment by cettoana** [comment]
Sorry, I'm here because of the help wanted tag, but it seems this issue has been closed.

Maybe you can try to use ES6 `arrow function` like

```js
arr.map((name, index) => {
  return <Field handler={this.handler} name={name} key={index} />
})
```

I think this should work.
